In [1]:
import pandas as pd

df = pd.DataFrame([
        ['green','M', 10.1, 'class1'],
        ['red', 'L',13.5,'class2'],
        ['bule', 'XL',15.3,'class1']
    ])
df.columns = ['color', 'size', 'price', 'classlabel']
df

color size  price classlabel
0  green    M   10.1     class1
1    red    L   13.5     class2
2   bule   XL   15.3     class1

In [2]:
# サイズを数値にマッピング
size_mapping ={'XL':3,'L':2, 'M':1}
df['size'] = df['size'].map(size_mapping)
df

color  size  price classlabel
0  green     1   10.1     class1
1    red     2   13.5     class2
2   bule     3   15.3     class1

In [3]:
import numpy as np

class_mapping = {label:idx for idx , label in enumerate(np.unique(df['classlabel']))}
print(class_mapping)

df['classlabel'] = df['classlabel'].map(class_mapping)
df

{'class1': 0, 'class2': 1}


color  size  price  classlabel
0  green     1   10.1           0
1    red     2   13.5           1
2   bule     3   15.3           0

In [4]:
# 元に戻す
inv_class_mapping={v:k for k ,v in class_mapping.items()}
print(inv_class_mapping)
df['classlabel'] = df['classlabel'].map(inv_class_mapping)
df

{0: 'class1', 1: 'class2'}


color  size  price classlabel
0  green     1   10.1     class1
1    red     2   13.5     class2
2   bule     3   15.3     class1

In [5]:
from sklearn.preprocessing import LabelEncoder

class_le = LabelEncoder()
y = class_le.fit_transform(df['classlabel'].values)
print(y)

y2 = class_le.inverse_transform(y)
print(y2)

[0 1 0]
['class1' 'class2' 'class1']


In [13]:
# 4.2.3
X = df[['color', 'size','price']].values
color_le = LabelEncoder()
X[:,0] = color_le.fit_transform(X[:,0])
X

array([[1, 1, 10.1],
       [2, 2, 13.5],
       [0, 3, 15.3]], dtype=object)

In [14]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(categorical_features=[0])
ohe.fit_transform(X).toarray()

array([[  0. ,   1. ,   0. ,   1. ,  10.1],
       [  0. ,   0. ,   1. ,   2. ,  13.5],
       [  1. ,   0. ,   0. ,   3. ,  15.3]])

In [16]:
# colorを文字列のままで（数値化しないで）エンコーダーにかけるとエラーになる。
from sklearn.preprocessing import OneHotEncoder
X = df[['color', 'size','price']].values
ohe = OneHotEncoder(categorical_features=[0])
ohe.fit_transform(X).toarray()

ValueError: could not convert string to float: 'bule'

In [8]:
#文字列から直接one-hotエンコードできる
pd.get_dummies(df[['color', 'size','price']])

size  price  color_bule  color_green  color_red
0     1   10.1           0            1          0
1     2   13.5           0            0          1
2     3   15.3           1            0          0